"""add position_id status to resume_data

Revision ID: 5ca1701cae02
Revises: 89f7c6f4eec3
Create Date: 2026-09-04 19:58:41.468672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca1701cae02'
down_revision: Union[str, Sequence[str], None] = '89f7c6f4eec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('resume_data', sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
    # position_id already added by partial migration, only create FK/index if missing
    try:
        op.create_index(op.f('ix_resume_data_position_id'), 'resume_data', ['position_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_foreign_key(None, 'resume_data', 'positions', ['position_id'], ['id'], ondelete='SET NULL')
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_data', type_='foreignkey')
    op.drop_index(op.f('ix_resume_data_position_id'), table_name='resume_data')
    op.drop_column('resume_data', 'status')
    op.drop_column('resume_data', 'position_id')
    # ### end Alembic commands ###
